version: '3.9'
services:

  dsp-agent:
    image: tecnativa/docker-socket-proxy:nightly
#    user: root
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=debug
      ## Variables match the URL prefix
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1
      - DELETE=1
      # GET Optons
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PLUGINS=0
      - SERVICES=1
      - SESSION=0
      - SWARM=1
      - SYSTEM=0
      - TASKS=1
      - VOLUMES=1
      # POST Options
      - CONTAINERS_CREATE=1
      - CONTAINERS_START=1
      - CONTAINERS_UPDATE=1
      # DELETE Options
      - CONTAINERS_DELETE=1
      - IMAGES_DELETE=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dock-overlay-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  dock-overlay-net:
    name: dock-overlay-net
    external: true
