version: '3.9'
services:

  # netbox
  netbox:
    networks:
      - dock-overlay-net
    ports:
      - 80:8080
  netbox-worker:
    networks:
      - dock-overlay-net
  netbox-housekeeping:
    networks:
      - dock-overlay-net

  # postgres
  postgres:
    networks:
      - dock-overlay-net

  # redis
  redis:
    networks:
      - dock-overlay-net
  redis-cache:
    networks:
      - dock-overlay-net

networks:
  dock-overlay-net:
    name: dock-overlay-net
    external: true
