version: '3.9'
services:
  jenkins-server:
    image: 3roin/jenkins:v0.1
    user: root
    volumes:
      - type: bind
        source: /mnt/jenkins/jenkins-data
        target: /var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - dock-overlay-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  dock-overlay-net:
    name: dock-overlay-net
    external: true
