version: '3.9'
services:
  server:
    image: 3roin/jenkins:v0.1
#    user: jenkins:jenkins
    user: root
    volumes:
     - type: bind
       source: /mnt/jenkins/jenkins-data
       target: /var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - agent_network
#      - portainer_agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  agent_network:
    driver: overlay
    attachable: true
#  portainer_agent_network:
#    external:
#      name: portainer_agent_network
