version: '3.8'

services:
  agent:
    image: portainer/agent:2.16.2-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - dock-overlay-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  server:
    image: portainer/portainer-ce:2.16.2-alpine
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - type: bind
        source: /mnt/nfs/docker-apps-data/portainer/data
        target: /data
    networks:
      - dock-overlay-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  dock-overlay-net:
    name: dock-overlay-net
    external: true
